import { Directive, inject, OnInit } from '@angular/core';
import { SortDirection } from '@angular/material/sort';
import { ActivatedRoute, Router } from '@angular/router';
import { isDate, isMoment } from 'moment';
import { ListStateService } from '../../services';
import { Filters, TableRequestParams } from '../../types';

/**
 * Base class for list components that persist filters, sorting, and pagination
 * state for the current route.
 *
 * Subclasses are expected to provide the activity key used to identify the list
 * and may override the object identifier used when navigating to a row detail.
 */
@Directive()
export abstract class BaseListComponent implements OnInit {
  /**
   * Active route that provides contextual information for the current list view.
   */
  protected route = inject(ActivatedRoute);

  /** Router used to identify the current list route. */
  protected readonly router = inject(Router);

  /** Service used to cache and restore list state. */
  protected readonly state = inject(ListStateService);

  /** Currently applied list filters. */
  protected currentFilters: Filters = {};

  /** Currently applied list sorting configuration. */
  protected currentSort: { active: string; direction: SortDirection } | null = null;

  /** Currently applied list pagination configuration. */
  protected currentPagination: { pageIndex: number; pageSize: number } | null = null;

  /**
   * Filter controls to synchronize after restoring cached list state.
   *
   * The object is supplied by a subclass through {@link setFilters} and is
   * updated in place when matching cached filter values are available.
   */
  protected filters: any;

  /**
   * URL without query parameters, used as the state cache key.
   */
  private get currentBaseUrl(): string {
    return this.router.url.split('?')[0];
  }

  /**
   * Restores the cached list state and initializes the component state.
   *
   * @returns Nothing. State restoration is performed synchronously.
   */
  ngOnInit(): void {
    this.restoreState();
  }

  protected applyFilters(): void {
    const filters: Filters = {};
    Object.keys(this.filters).forEach((k) => {
      if (this.filters[k]) {
        filters[k] = this.getFilterValue(k, this.filters[k]);
      }
    });
    this.currentFilters = filters;
  }

  /**
   * Gets the activity identifier used by the list.
   */
  protected abstract getActivity(): string;

  protected getFilterValue(_: string, value: any): any {
    if (isDate(value) || isMoment(value)) {
      return value.toISOString();
    }
    if (typeof value === 'string') {
      return `%${value}%`;
    }
    return value;
  }

  /**
   * Returns the property name used to resolve the row identifier when navigating.
   *
   * @returns The object key used for route navigation.
   */
  protected getObjectId(): string {
    return 'id';
  }

  /**
   * Persists the latest table state after filters, sorting, or pagination change.
   *
   * @param params The request parameters generated by the list table.
   * @returns Nothing.
   */
  protected onListStateChange(params: TableRequestParams): void {
    this.currentSort = {
      active: params.sort || '',
      direction: params.direction || '',
    };
    this.currentPagination = {
      pageIndex: params.pageIndex,
      pageSize: params.pageSize,
    };
    this.currentFilters = params.filters;

    this.saveState();
  }

  /**
   * Navigates to the selected row or opens a URL when the item contains one.
   *
   * @param item The row item being clicked.
   */
  protected onRowClick(item: any): void {
    if (item.url) {
      window.open(item.url, '_blank');
      return;
    }
    this.router.navigate([(item as any)[this.getObjectId()]], { relativeTo: this.route });
  }

  /**
   * Hook invoked after cached state has been restored.
   *
   * The default implementation synchronizes the supplied filter controls with
   * the restored values. Subclasses may override this to apply additional
   * logic after state recovery.
   *
   * @returns Nothing.
   */
  protected onStateRestored(): void {
    if (!this.currentFilters) {
      return;
    }

    Object.keys(this.currentFilters).forEach((k) => {
      if (typeof this.currentFilters[k] === 'string') {
        this.filters[k] = (this.currentFilters[k] as string)?.replaceAll('%', '');
      } else {
        this.filters[k] = this.currentFilters[k];
      }
    });
  }

  /**
   * Restores the cached state for the current route when available.
   *
   * The cache key is derived from the route URL without its query string.
   *
   * @returns Nothing. The component state is updated when cached data exists.
   */
  private restoreState(): void {
    const cached = this.state.getCache(this.currentBaseUrl);
    if (cached) {
      this.currentFilters = { ...cached.filters };
      this.currentSort = { ...cached.sort };
      if (cached.pagination) {
        this.currentPagination = { ...cached.pagination };
      }

      this.onStateRestored();
    }
  }

  /**
   * Saves the current filters, sorting, and pagination state.
   *
   * @returns Nothing.
   */
  protected saveState(): void {
    this.state.setCache(this.currentBaseUrl, {
      filters: this.currentFilters,
      sort: this.currentSort,
      pagination: this.currentPagination,
    });
  }
}
